const API='https://api.github.com';
const headers=(token)=>({...token?{Authorization:`Bearer ${token}`}:{},Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'});
function encode64(text){const bytes=new TextEncoder().encode(text);let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
function decode64(text){const bin=atob(text.replace(/\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function requireToken(env){if(typeof env.GITHUB_TOKEN!=='string'||!env.GITHUB_TOKEN.trim())throw new Error('GITHUB_TOKEN is not configured')}
async function gitBlobSha(text){const bytes=new TextEncoder().encode(text);const header=new TextEncoder().encode(`blob ${bytes.length}\0`);const all=new Uint8Array(header.length+bytes.length);all.set(header);all.set(bytes,header.length);const digest=await crypto.subtle.digest('SHA-1',all);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function readRepoFile(env,path){const repo=env.GITHUB_REPO||'ARARAT33/AWEARCHIVE',branch=env.GITHUB_BRANCH||'main';const raw=`https://raw.githubusercontent.com/${repo}/${encodeURIComponent(branch)}/${path.split('/').map(encodeURIComponent).join('/')}`;const r=await fetch(raw,{headers:{accept:'text/plain'}});if(r.status===404)return {exists:false,sha:null,data:null};if(!r.ok)throw new Error(`Archive read failed ${r.status}`);const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Archive JSON is invalid')};return {exists:true,sha:await gitBlobSha(text),data}}
export async function writeRepoFile(env,path,data,sha,message){requireToken(env);const repo=env.GITHUB_REPO||'ARARAT33/AWEARCHIVE',branch=env.GITHUB_BRANCH||'main',token=env.GITHUB_TOKEN.trim();const r=await fetch(`${API}/repos/${repo}/contents/${path}`,{method:'PUT',headers:headers(token),body:JSON.stringify({message,content:encode64(JSON.stringify(data,null,2)+'\n'),branch,...sha?{sha}: {}})});if(!r.ok){const text=await r.text();throw new Error(`GitHub write failed ${r.status}: ${text.slice(0,500)}`)}return r.json()}
export async function mutateRepoFile(env,path,mutator,message){requireToken(env);for(let i=0;i<3;i++){const f=await readRepoFile(env,path);const next=await mutator(f.data??[]);try{return await writeRepoFile(env,path,next,f.sha,message)}catch(e){if(i===2)throw e}}throw new Error('GitHub write conflict')}
