import {isAdmin,makeSession,cookie,clearCookie} from '../../_shared/auth.js';
import {readRepoFile,writeRepoFile} from '../../_shared/github.js';
const out=(data,status=200,headers={})=>Response.json(data,{status,headers});
async function readArchive(env){const f=await readRepoFile(env,'archive.json');const d=f.data;return Array.isArray(d)?d:[]}
const clean=(x)=>String(x??'').trim();
const slugify=(x)=>clean(x).toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);
function validate(x){if(!x||!clean(x.title)||!clean(x.url)||!['file','video','image','webpage','other'].includes(x.type))return 'title, url and a valid type are required';try{new URL(x.url)}catch{return 'URL must be absolute (https://...)'}if(x.thumbnail){try{new URL(x.thumbnail)}catch{return 'Thumbnail URL is invalid'}}return null}
function normalize(x,old={}){const now=new Date().toISOString();return {...old,...x,id:clean(x.id)||old.id||crypto.randomUUID(),title:clean(x.title),slug:slugify(x.slug)||slugify(x.title),description:clean(x.description),type:['file','video','image','webpage','other'].includes(x.type)?x.type:'other',status:x.status==='hidden'?'hidden':'active',url:clean(x.url),thumbnail:clean(x.thumbnail)||undefined,tags:[...new Set((Array.isArray(x.tags)?x.tags:typeof x.tags==='string'?x.tags.split(','):[]).map(clean).filter(Boolean))].slice(0,50),createdAt:old.createdAt||x.createdAt||now,updatedAt:now}}
async function save(env,items,message){const f=await readRepoFile(env,'archive.json');return writeRepoFile(env,'archive.json',items,f.sha,message)}
export async function onRequest(context){const req=context.request,env=context.env;const raw=context.params?.path;const path=Array.isArray(raw)?raw.join('/'):String(raw||'');
 if(req.method==='POST'&&path==='login'){const b=await req.json().catch(()=>null);const u=typeof b?.username==='string'?b.username:'';const p=typeof b?.password==='string'?b.password:'';if(typeof env.ADMIN_USERNAME!=='string'||typeof env.ADMIN_PASSWORD!=='string'||typeof env.ADMIN_SESSION_SECRET!=='string')return out({error:'Admin authentication is not configured'},503);if(u!==env.ADMIN_USERNAME||p!==env.ADMIN_PASSWORD)return out({error:'Invalid credentials'},401);return out({ok:true},200,{'Set-Cookie':cookie(await makeSession(env,u))})}
 if(req.method==='POST'&&path==='logout')return out({ok:true},200,{'Set-Cookie':clearCookie()});
 if(!await isAdmin(req,env))return out({error:'Unauthorized'},401);
 if(req.method==='GET')return out({ok:true,admin:true,storage:'ARARAT33/AWEArchiveDB/archive.json',items:await readArchive(env)});
 try{let items=await readArchive(env);
  if(req.method==='POST'&&path==='import'){const b=await req.json().catch(()=>null);if(!Array.isArray(b?.items))return out({error:'items array required'},400);if(b.items.length>10000)return out({error:'Import limit is 10,000 records per operation'},400);const next=[];for(const rawItem of b.items){const x=normalize(rawItem);const error=validate(x);if(error)return out({error:`Invalid item ${x.title||x.id}: ${error}`},400);next.push(x)}const ids=new Set();for(const x of next){if(ids.has(x.id))return out({error:`Duplicate id: ${x.id}`},400);ids.add(x.id)}await save(env,next,'admin: bulk import catalog');return out({ok:true,imported:next.length,storage:'AWEArchiveDB'})}
  if(req.method==='PUT'){const x=await req.json().catch(()=>null);const error=validate(x);if(error)return out({error},400);const i=items.findIndex(a=>a.id===x.id);const n=normalize(x,i>=0?items[i]:{});if(i>=0)items[i]=n;else items.unshift(n);await save(env,items,`admin: ${i>=0?'update':'add'} ${n.slug}`);return out({ok:true,item:n,action:i>=0?'updated':'created',storage:'AWEArchiveDB'})}
  if(req.method==='DELETE'){const b=await req.json().catch(()=>({}));const ids=Array.isArray(b.ids)?b.ids.filter(Boolean):[b.id].filter(Boolean);if(!ids.length)return out({error:'id or ids required'},400);const before=items.length;items=items.filter(x=>!ids.includes(x.id));if(items.length===before)return out({error:'No matching items found'},404);await save(env,items,`admin: delete ${before-items.length} archive item(s)`);return out({ok:true,deleted:before-items.length,remaining:items.length})}
  if(req.method==='PATCH'){const b=await req.json().catch(()=>null);if(!b?.id)return out({error:'id required'},400);const i=items.findIndex(x=>x.id===b.id);if(i<0)return out({error:'Item not found'},404);const allowed=['title','slug','description','type','status','url','thumbnail','tags'];const patch={};for(const k of allowed)if(k in b)patch[k]=b[k];const n=normalize({...items[i],...patch},items[i]);const error=validate(n);if(error)return out({error},400);items[i]=n;await save(env,items,`admin: patch ${n.slug}`);return out({ok:true,item:n})}
  return out({error:'Method not allowed'},405)}catch(e){return out({error:e instanceof Error?e.message:'Admin request failed'},500)}}
