import {isAdmin,makeSession,cookie,clearCookie} from '../../_shared/auth.js';
import {writeRepoFile} from '../../_shared/github.js';
const out=(data,status=200,headers={})=>Response.json(data,{status,headers});
async function readArchive(request){try{const r=await fetch(new URL('/data/archive.json',request.url).toString(),{headers:{accept:'application/json'}});if(!r.ok)return [];const d=await r.json();return Array.isArray(d)?d:[]}catch{return []}}
async function repoSnapshot(env){const repo=env.GITHUB_REPO||'ARARAT33/AWEARCHIVE',branch=env.GITHUB_BRANCH||'main',token=String(env.GITHUB_TOKEN||'').trim();if(!token)throw new Error('GITHUB_TOKEN is not configured');const r=await fetch(`https://api.github.com/repos/${repo}/contents/data/archive.json?ref=${encodeURIComponent(branch)}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)throw new Error(`GitHub read failed ${r.status}`);return (await r.json()).sha}
const clean=(x)=>String(x??'').trim();
const slugify=(x)=>clean(x).toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);
function validate(x){if(!x||!clean(x.title)||!clean(x.url)||!['file','video','image','webpage','other'].includes(x.type))return 'title, url and a valid type are required';try{new URL(x.url)}catch{return 'URL must be absolute (https://...)'}if(x.thumbnail){try{new URL(x.thumbnail)}catch{return 'Thumbnail URL is invalid'}}return null}
async function commit(env,items,sha,message){return writeRepoFile(env,'data/archive.json',items,sha,message)}
export async function onRequest(context){const req=context.request,env=context.env;const raw=context.params?.path;const path=Array.isArray(raw)?raw.join('/'):String(raw||'');
 if(req.method==='POST'&&path==='login'){const b=await req.json().catch(()=>null);const u=typeof b?.username==='string'?b.username:'';const p=typeof b?.password==='string'?b.password:'';if(typeof env.ADMIN_USERNAME!=='string'||typeof env.ADMIN_PASSWORD!=='string'||typeof env.ADMIN_SESSION_SECRET!=='string')return out({error:'Admin authentication is not configured'},503);if(u!==env.ADMIN_USERNAME||p!==env.ADMIN_PASSWORD)return out({error:'Invalid credentials'},401);return out({ok:true},200,{'Set-Cookie':cookie(await makeSession(env,u))})}
 if(req.method==='POST'&&path==='logout')return out({ok:true},200,{'Set-Cookie':clearCookie()});
 if(!await isAdmin(req,env))return out({error:'Unauthorized'},401);
 if(req.method==='GET')return out({ok:true,admin:true,items:await readArchive(req)});
 try{let items=await readArchive(req);
  if(req.method==='PUT'){const x=await req.json().catch(()=>null);const error=validate(x);if(error)return out({error},400);x.id=clean(x.id)||crypto.randomUUID();x.slug=slugify(x.slug)||slugify(x.title)||x.id;x.description=clean(x.description);x.tags=[...new Set((Array.isArray(x.tags)?x.tags:[]).map(clean).filter(Boolean))].slice(0,50);x.status=x.status==='hidden'?'hidden':'active';x.thumbnail=clean(x.thumbnail)||undefined;const now=new Date().toISOString();const i=items.findIndex(a=>a.id===x.id);if(i>=0){x.createdAt=items[i].createdAt||now;items[i]={...items[i],...x,updatedAt:now}}else{items.unshift({...x,createdAt:now,updatedAt:now})}const sha=await repoSnapshot(env);await commit(env,items,sha,`admin: ${i>=0?'update':'add'} ${x.slug}`);return out({ok:true,item:x,action:i>=0?'updated':'created'})}
  if(req.method==='DELETE'){const b=await req.json().catch(()=>({}));const ids=Array.isArray(b.ids)?b.ids.filter(Boolean):[b.id].filter(Boolean);if(!ids.length)return out({error:'id or ids required'},400);const before=items.length;items=items.filter(x=>!ids.includes(x.id));if(items.length===before)return out({error:'No matching items found'},404);const sha=await repoSnapshot(env);await commit(env,items,sha,`admin: delete ${before-items.length} archive item(s)`);return out({ok:true,deleted:before-items.length,remaining:items.length})}
  if(req.method==='PATCH'){const b=await req.json().catch(()=>null);if(!b?.id)return out({error:'id required'},400);const i=items.findIndex(x=>x.id===b.id);if(i<0)return out({error:'Item not found'},404);const allowed=['title','slug','description','type','status','url','thumbnail','tags'];for(const k of allowed)if(k in b)items[i][k]=b[k];items[i].updatedAt=new Date().toISOString();const error=validate(items[i]);if(error)return out({error},400);const sha=await repoSnapshot(env);await commit(env,items,sha,`admin: patch ${items[i].slug}`);return out({ok:true,item:items[i]})}
  return out({error:'Method not allowed'},405)}catch(e){return out({error:e instanceof Error?e.message:'Admin request failed'},500)}}
